test:
  image:
    name: docker/compose:1.24.0
    entrypoint: ["/bin/sh", "-c"]
  services:
    - docker:dind
  script:
    - docker-compose up --build --abort-on-container-exit --exit-code-from tests
